language: objective-c
matrix:
    include:
        - osx_image: xcode10.2

before_install:
    - brew update
    - brew install carthage
    - cd ./ADVIS
    - carthage bootstrap --no-use-binaries --platform ios

script:
    - xcodebuild test -scheme ADVIS -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.2,name=iPad Pro (12.9-inch) (3rd generation)' -configuration Debug | xcpretty -c
    - bash <(curl -s https://codecov.io/bash) t {CODECOV_TOKEN}
